9. 댓글
create sequence seq_cpp_reply_no

ALTER TABLE SCOTT.CPP_REPLY
 DROP PRIMARY KEY CASCADE;

DROP TABLE SCOTT.CPP_REPLY CASCADE CONSTRAINTS;

CREATE TABLE SCOTT.CPP_REPLY
(
  REPLY_NO       NUMBER,
  BOARD_NO       NUMBER,
  MEMBER_ID      VARCHAR2(20 BYTE),
  REPLY_CONTENT  VARCHAR2(2000 BYTE),
  CREATE_DATE    DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


#NAME?
#NAME?

ALTER TABLE SCOTT.CPP_REPLY ADD (
  PRIMARY KEY
  (REPLY_NO)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE SCOTT.CPP_REPLY ADD (
  CONSTRAINT FK_CPP_REPLY_BOARD_NO 
  FOREIGN KEY (BOARD_NO) 
  REFERENCES SCOTT.CPP_BOARD (BOARD_NO)
  ENABLE VALIDATE,
  CONSTRAINT FK_CPP_REPLY_MEMBER_ID 
  FOREIGN KEY (MEMBER_ID) 
  REFERENCES SCOTT.CPP_MEMBER (MEMBER_ID)
  ENABLE VALIDATE);
