4. 로그인
DROP TABLE SCOTT.CPP_LOGIN CASCADE CONSTRAINTS;

CREATE TABLE SCOTT.CPP_LOGIN
(
  MEMBER_ID    VARCHAR2(20 BYTE),
  CREATE_DATE  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE SCOTT.CPP_LOGIN ADD (
  CONSTRAINT FK_CPP_LOGIN_MEMBER_ID 
  FOREIGN KEY (MEMBER_ID) 
  REFERENCES SCOTT.CPP_MEMBER (MEMBER_ID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON SCOTT.CPP_LOGIN TO SYSTEM;
