1. 메시지
DROP TABLE SCOTT.CPP_MESSAGE CASCADE CONSTRAINTS;

CREATE TABLE SCOTT.CPP_MESSAGE
(
  SEND_ID     VARCHAR2(20 BYTE),
  RECEIVE_ID  VARCHAR2(20 BYTE),
  MESSAGE     VARCHAR2(200 BYTE),
  MDATE       DATE,
  READ        VARCHAR2(2 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;