10. 업무
create sequence seq_cpp_job_no

ALTER TABLE SCOTT.CPP_JOB
 DROP PRIMARY KEY CASCADE;

DROP TABLE SCOTT.CPP_JOB CASCADE CONSTRAINTS;

CREATE TABLE SCOTT.CPP_JOB
(
  JOB_NO       NUMBER,
  MEMBER_ID    VARCHAR2(20 BYTE),
  PROJECT_NO   NUMBER,
  JOB_TITLE    VARCHAR2(200 BYTE),
  JOB_CONTENT  VARCHAR2(2000 BYTE),
  CREATE_DATE  DATE,
  START_DATE   DATE,
  END_DATE     DATE,
  JOB_TYPE     VARCHAR2(30 BYTE),
  JOB_STATUS   VARCHAR2(30 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


#NAME?
#NAME?

ALTER TABLE SCOTT.CPP_JOB ADD (
  PRIMARY KEY
  (JOB_NO)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE SCOTT.CPP_JOB ADD (
  CONSTRAINT FK_CPP_JOB_MEMBER_ID 
  FOREIGN KEY (MEMBER_ID) 
  REFERENCES SCOTT.CPP_MEMBER (MEMBER_ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_CPP_JOB_PROJECT_NO 
  FOREIGN KEY (PROJECT_NO) 
  REFERENCES SCOTT.CPP_PROJECT (PROJECT_NO)
  ENABLE VALIDATE);
