3. 프로젝트정보
create sequence seq_cpp_project_no

ALTER TABLE SCOTT.CPP_PROJECT
 DROP PRIMARY KEY CASCADE;

DROP TABLE SCOTT.CPP_PROJECT CASCADE CONSTRAINTS;

CREATE TABLE SCOTT.CPP_PROJECT
(
  PROJECT_NO      NUMBER,
  PROJECT_NAME    VARCHAR2(50 BYTE),
  PROJECT_STATUS  VARCHAR2(20 BYTE),
  PROJECT_DETAIL  VARCHAR2(400 BYTE),
  ORDER_COMPANY   VARCHAR2(50 BYTE),
  OBTAIN_COMPANY  VARCHAR2(50 BYTE),
  PROJECT_BUDGET  NUMBER,
  START_DATE      DATE,
  END_DATE        DATE,
  MEMBER_ID       VARCHAR2(40 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


#NAME?
#NAME?

ALTER TABLE SCOTT.CPP_PROJECT ADD (
  PRIMARY KEY
  (PROJECT_NO)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
