7. 프로젝트 멤버
DROP TABLE SCOTT.CPP_PROJECT_MEMBER CASCADE CONSTRAINTS;

CREATE TABLE SCOTT.CPP_PROJECT_MEMBER
(
  MEMBER_ID    VARCHAR2(20 BYTE),
  PROJECT_NO   NUMBER,
  GRADE        VARCHAR2(20 BYTE),
  CREATE_DATE  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE SCOTT.CPP_PROJECT_MEMBER ADD (
  CONSTRAINT FK_CPP_PROJECTMB_MEMBER_ID 
  FOREIGN KEY (MEMBER_ID) 
  REFERENCES SCOTT.CPP_MEMBER (MEMBER_ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_CPP_PROJECTMB_PROJECT_NO 
  FOREIGN KEY (PROJECT_NO) 
  REFERENCES SCOTT.CPP_PROJECT (PROJECT_NO)
  ENABLE VALIDATE);
