2. 회원
ALTER TABLE SCOTT.CPP_MEMBER
 DROP PRIMARY KEY CASCADE;

DROP TABLE SCOTT.CPP_MEMBER CASCADE CONSTRAINTS;

CREATE TABLE SCOTT.CPP_MEMBER
(
  MEMBER_ID               VARCHAR2(20 BYTE),
  MEMBER_PW               VARCHAR2(30 BYTE),
  MEMBER_NAME             VARCHAR2(20 BYTE),
  MEMBER_GENDER           VARCHAR2(10 BYTE),
  MEMBER_PHONE            VARCHAR2(15 BYTE),
  MEMBER_EMAIL            VARCHAR2(100 BYTE),
  MEMBER_COMPANY          VARCHAR2(50 BYTE),
  MEMBER_DEPT             VARCHAR2(50 BYTE),
  MEMBER_RANK             VARCHAR2(50 BYTE),
  CREATE_DATE             DATE,
  LAST_LOGIN_DATE         DATE,
  LEAVE_DATE              DATE,
  MEMBER_STATUS           VARCHAR2(4 BYTE),
  MEMBER_IMAGE_NAME       VARCHAR2(50 BYTE),
  MEMBER_IMAGE_SAVE_NAME  VARCHAR2(100 BYTE),
  MEMBER_IMAGE_PATH       VARCHAR2(50 BYTE),
  MEMBER_IMAGE_SIZE       NUMBER,
  SEARCH_STATUS           VARCHAR2(4 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


#NAME?
#NAME?

ALTER TABLE SCOTT.CPP_MEMBER ADD (
  PRIMARY KEY
  (MEMBER_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
